### ISSUE TITLE
HDF5 error with Ubuntu 18.04 LTE

### ISSUE THREAD

**Issue by haberlmatt** [CRBS/cdeep3m#57]
When doing local installs on Ubuntu 18.04LTE an error shows up as: << error: h5write: support for HDF5 IO was unavailable or disabled when Octave was built >>
everything works fine with Ubuntu 16

**Comment by coleslaw481** [comment]
Ubuntu 18.04 uses a newer version of octave (4.2 I believe). You could try a newer version of the hdf5oct libraryfrom this repo:

https://github.com/stegro/hdf5oct

The commit being used is b047e6e611e874b02740e7465f5d139e74f9765f and there are a couple commits after this one. See the basic_cloudformation.json file on how the above commit is being downloaded.

**Comment by TITC** [comment]
Hi,

What's the number of **b047e6e611e874b02740e7465f5d139e74f9765f**,and how do you solve it?
```
Starting Training data Preprocessing
Training Image Path:

./most/soma/train/images
Reading file: ./most/soma/train/images/x.001.png
Reading file: ./most/soma/train/images/x.002.png
........................
Verifying images
Reading file: ./most/soma/train/labels/x.001.png
Reading file: ./most/soma/train/labels/x.002.png
...........................
Verifying labels
Checking image dimensions
Augmenting training data 1-8 and 9-16
Create variation 1 and 9
Saving: ./soma_augmented/training_full_stacks_v1.h5
error: h5write: support for HDF5 IO was unavailable or disabled when Octave was built
error: called from
    PreprocessTrainingData at line 96 column 5
````
>machine
````
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
````
>octave version
````
GNU Octave, version 4.2.2
````
>hdf5 version
````
Package: libhdf5-dev
Status: install ok installed
Priority: optional
Section: libdevel
Installed-Size: 11294
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: hdf5
Version: 1.10.0-patch1+docs-4
````

**Comment by haberlmatt** [comment]
This bug is only concerning local installs with CDeep3M Version 1,
as you mentioned you are using the Colab installation of CDeep3M2 this issue is resolved

**Comment by TITC** [comment]
thanks, I will try it.
