### ISSUE TITLE
Watershed error

### ISSUE THREAD

**Issue by MatthewBM** [CRBS/cdeep3m#61]
line 90 in Apply3DWaterhsed.m is:
L = watershed(hmtransf(imfilter(ensMod, h), hm3d),6);
and should be:
L = watershed(hmtransf(imfilter(ensMod, h), hm3d,6),6);

**Comment by haberlmatt** [comment]
I think this was a difference between the filter function that is implemented in octave, versus the one that is implemented in Matlab
Can you check in Octave?

**Comment by MatthewBM** [comment]
It's the hmtransf function that's in CDeep3M's scripts/functions:

function img = hmtransf(img, t, connectiv)
