### ISSUE TITLE
Blank prediction results

### ISSUE THREAD

**Issue by camcondylis** [CRBS/cdeep3m#69]
Hello, 
I have been running into an issue where the prediction results from a trained model are blank.  I have double checked that my input training images and labels are correct, and that the input prediction images have similar pixel histograms to the training data.  any idea what is causing this?
Thanks,
Cam

**Comment by haberlmatt** [comment]
Hi @camcondylis,
can you send an email with the training images to cdeep3m <at> gmail.com for us to be able to reproduce what might be causing it?
Thanks,
Matt
